version: '3.3'

services:
  jenkins:
    container_name: jenkins
    image: andreav/jenkins-jcasc
    build:
      context: ./jenkins-image
    ports:
      - 8888:8080
      - 55555:55555
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock://var/run/docker.sock
      - ./jcasc_configs:/var/jenkins_home/jcasc_configs
    secrets:
      - source: github
      - source: adminpw
      - source: google-services-json
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc_configs
secrets:
  github:
    file: ./secrets/github
  adminpw:
    file: ./secrets/adminpw
  google-services-json:
      file: ./secrets/google-services.json  
volumes:
  jenkins_home:
