version: '3.3'

services:
  jenkins:
    image: andreav/jenkins-ns
    build: #TODO: Once plugin installation is handled through c-as-c this can be removed and replaced with 'image'.
      context: ./jenkins-image
    ports:
      - 8888:8080
      - 55555:55555
    volumes:
      - jenkins_home:/var/jenkins_home
      # - \\.\pipe\docker_engine:\\.\pipe\docker_engine
      - ./jcasc_configs:/var/jenkins_home/jcasc_configs
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe

    # secrets:
    #   - source: github  #Github username with password as an example.
    #     target: C:\temp\github
    #   - source: adminpw  #Initial administrator user password.
    #     target: C:\temp\adminpwd
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jcasc_configs
secrets: #Be careful with newlines in your secrets, make sure to remove them before running docker-compose up.
  github:
    file: ./secrets/github
  adminpw:
    file: ./secrets/adminpw
volumes:
  jenkins_home:
