jobs:
  - script: >
      folder('testjobs')  
  - script: >
      freeStyleJob('testjobs/test-frestyle-job') {
        scm {
          github('andreav/nativescript-vue-test', 'master')
        }
        steps {
          shell('echo Hello World!')
        }
        publishers {
          archiveArtifacts('app/main.ts')
        }        
      }  
  - script: >
      pipelineJob('testjobs/test-pipeline-job-inline') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }
  - script: >
      pipelineJob('testjobs/test-pipeline-on-win-slave') {
        definition {
          cps {
            script("""\
            pipeline {
              agent {
                label 'windows'
              }
              stages {
                stage ('prepare-env') {
                  steps {
                    withCredentials([file(credentialsId: 'google_services_json', variable: 'VAR_GOOGLE_SERVICES_JSON')]) {
                      bat label: '', script: 'copy %VAR_GOOGLE_SERVICES_JSON% google-services.json'
                    }
                  }
                }
              }
            }""".stripIndent())
          }
        }
      }
  - script: >
      pipelineJob('testjobs/test-pipeline-job-jekinsfile') {
        definition {
          cpsScm {
            scm {
              github('andreav/nativescript-vue-test', 'master')
            }
          }
        }
        properties {
          disableConcurrentBuilds()
          disableResume()          
        }
      }
